# Generated by Django 4.0.1 on 2022-10-17 12:58

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('school', models.CharField(max_length=64)),
                ('program', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('job_role', models.CharField(max_length=64)),
                ('company', models.CharField(max_length=64)),
                ('achievement', models.TextField(blank=True, db_index=True, help_text='Required')),
                ('responsibilities', models.TextField(blank=True, db_index=True, help_text='Required')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('spec_name',),
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(db_index=True)),
                ('client_name', models.CharField(max_length=64)),
                ('testimony', models.TextField(blank=True, db_index=True, help_text='Required')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(db_index=True, max_length=64, unique=True)),
                ('skill_set1', models.CharField(max_length=64)),
                ('skill_set2', models.CharField(max_length=64)),
                ('skill_set3', models.CharField(max_length=64)),
                ('skill_set4', models.CharField(max_length=64)),
                ('skill_set5', models.CharField(max_length=64)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPortfolioApp.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=64)),
                ('about_me', models.TextField(blank=True, db_index=True, help_text='Required')),
                ('Location', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPortfolioApp.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(db_index=True)),
                ('project_name', models.CharField(max_length=64)),
                ('project_url', models.URLField(db_index=True)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPortfolioApp.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course_school', models.CharField(max_length=64)),
                ('course', models.CharField(max_length=64)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPortfolioApp.specialty')),
            ],
        ),
    ]
