# Generated by Django 4.0.1 on 2022-10-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_set1',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_set2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_set3',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_set4',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_set5',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
