# Generated by Django 4.0.1 on 2022-10-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolioApp', '0003_portfolio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
