# Generated by Django 4.0.1 on 2022-10-23 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolioApp', '0004_testimonial_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='slug',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
